site_title: "Pete Fowler"
site_description: "Full Stack Software Engineer"
email: fowler.pete@gmail.com
socials:
    twitter: "https://google.com"
    linkedin: "https://linkedin.com/in/pete-fowler"
    github: "https://github.com/pete-fowler"
main:
    headings:
        - "I am Pete Fowler"
        - "Full Stack Software Engineer (React, C# / .NET, AWS)"
    paragraphs:
        - Full stack software engineer with 2.5 years of experience building a financial data integration SaaS product. Led a complete rebuild of the team’s web app using JavaScript, TypeScript, React, C#/.NET, Entity Framework Core and SQL, with testing in Jest, React Testing Library, xUnit, and Moq. Utilized AWS services including MySQL RDS, EC2, ECS with Docker, S3, Lambda, and EventBridge.

        - Passionate about continuous improvement, clean code, and best practices (where they exist). Dedicated rock climber and runner based in Colorado. Names variables like a first born child."
    button:
        text: "Get in touch"
        link: "mailto:fowler.pete@gmail.com"

about:
    title: "About Me"
    paragraphs:
        - "I am a full stack software engineer at Calance, on a team based in Boulder, Colorado. Our team primarily integrates financial data between project management and accounting software for construction industry clients. This is done with a number of apps in C# / .NET with a service oriented architecture deployed to Amazon Web Services."
        - "My contributions to this team include: leading a complete rebuild and upgrade of our customer facing web app, adding new financial data integrations, building new full stack applications that clients can use from within the Procore website, taking over development, maintenance and customer support of a line of data integrations between Procore and NetSuite, writing an OAuth 2.0 microservice and contributing across other microservices."
        - "I changed careers to software development in 2022. This change and previous changes demonstrate a strong ability to quickly adapt, learn, add value, and continue learning, and I've gained high level experience in team collaboration and problem solving through previous careers in journalism, private investigation, and health care."

get_in_touch:
    title: "Get in touch"
    paragraphs:
        - ""
    button:
        text: "Send me an Email"
        link: "mailto:fowler.pete@gmail.com"
