site_title: "Ram Ghale"
site_description: "Software Engineer and Designer"
email: ram@ghale.np
socials:
  twitter: "https://twitter.com/ramghale"
  linkedin: "https://linkedin.com/in/ramghale"
  github: "https://github.com/ramghale"
main:
  headings: 
    - "I am Ram Ghale"
    - "Software Engineer and Designer"
  paragraphs:
    - "I love to build things that make a difference in people's lives. I am passionate about technology, business, and storytelling. I am always looking for new opportunities to learn and grow."
  button:
    text: "Get in touch"
    link: "https://ghale.np"

about:
  title: "About Me"
  paragraphs: 
    - "I am a strong advocate for diversity and inclusion in tech, and I am always looking for ways to give back to the community. I am a mentor, speaker, and writer. I am also a co-founder of a tech community in Nepal."
    - "I am a lifelong learner and I am always looking for new opportunities to learn and grow. I am currently learning about entrepreneurship, business, and storytelling. I am also working on a few side projects and businesses."

get_in_touch:
  title: "Get in touch"
  paragraphs:
    - "In case you would like to get in touch with me, you can always send me an email"
  button:
    text: "Send me an Email"
    link: "mailto://ram@ghale.np"